add_library(VISRInstrumentation INTERFACE)
add_library(VISR::Instrumentation ALIAS VISRInstrumentation)

if(VISR_ENABLE_TRACY)
  find_package(Tracy CONFIG REQUIRED)
  target_link_libraries(VISRInstrumentation INTERFACE Tracy::TracyClient)
  target_compile_definitions(VISRInstrumentation INTERFACE TRACY_ENABLE=1)
  message(STATUS "VISR profiling: Tracy CPU, GPU, and allocation events enabled")
else()
  find_package(mimalloc CONFIG REQUIRED)
  if(TARGET mimalloc::mimalloc)
    target_link_libraries(VISRInstrumentation INTERFACE mimalloc::mimalloc)
  elseif(TARGET mimalloc)
    target_link_libraries(VISRInstrumentation INTERFACE mimalloc)
  else()
    message(FATAL_ERROR "mimalloc package did not provide a usable CMake target")
  endif()
  message(STATUS "VISR allocator: mimalloc")
endif()

function(visr_enable_runtime_instrumentation target)
  target_link_libraries(${target} PRIVATE VISR::Instrumentation)
  if(VISR_ENABLE_TRACY)
    target_sources(${target} PRIVATE
      "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../Core/src/TracyAllocator.cpp")
  endif()
endfunction()
