add_library(ARUIInstrumentation INTERFACE)
add_library(ARUI::Instrumentation ALIAS ARUIInstrumentation)

if(ARUI_ENABLE_TRACY)
  find_package(Tracy CONFIG REQUIRED)
  target_link_libraries(ARUIInstrumentation INTERFACE Tracy::TracyClient)
  target_compile_definitions(ARUIInstrumentation INTERFACE TRACY_ENABLE=1)
  message(STATUS "ARUI profiling: Tracy CPU, GPU, and allocation events enabled")
else()
  find_package(mimalloc CONFIG REQUIRED)
  if(TARGET mimalloc::mimalloc)
    target_link_libraries(ARUIInstrumentation INTERFACE mimalloc::mimalloc)
  elseif(TARGET mimalloc)
    target_link_libraries(ARUIInstrumentation INTERFACE mimalloc)
  else()
    message(FATAL_ERROR "mimalloc package did not provide a usable CMake target")
  endif()
  message(STATUS "ARUI allocator: mimalloc")
endif()

function(arui_enable_runtime_instrumentation target)
  target_link_libraries(${target} PRIVATE ARUI::Instrumentation)
  if(ARUI_ENABLE_TRACY)
    target_sources(${target} PRIVATE
      "${CMAKE_SOURCE_DIR}/Core/src/TracyAllocator.cpp")
  endif()
endfunction()
